# Use the official OpenJDK base image
FROM adoptopenjdk:11-jre-hotspot

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file into the container
COPY target/stc-0.0.1-SNAPSHOT.jar  app.jar

# Expose the port on which your Spring Boot app runs (replace 8080 with your app's port)
EXPOSE 7070

# Run the Spring Boot application when the container starts
CMD ["java", "-jar", "app.jar"]